name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual runs
  workflow_dispatch:
  # Allow to be invoked from other workflows
  workflow_call:

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.2.x'

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build libpks
        run: cmake --build build --target libpks

      - name: Build and run tests
        run: |
          cmake --build build --target libpks_tests
          ./build/tests/libpks_tests

      - name: Build and run sample_app
        run: |
          cmake --build build --target sample_app
          ./build/src/apps/sample_app
