name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual runs

permissions:
  contents: write

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.2.x'

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build libpks
        run: cmake --build build --target libpks

      - name: Build and run tests
        run: |
          cmake --build build --target libpks_tests
          ./build/tests/libpks_tests

      - name: Build and run sample_app
        run: |
          cmake --build build --target sample_app
          ./build/src/apps/sample_app

      - name: Copy libpks build artifacts to dist folder
        run: |
          mkdir -p dist
          cp ./build/src/libpks/liblibpks.a dist/libpks.a
          
          mkdir -p dist/include
          SOURCE_INCLUDE_DIR=src/libpks/include/
          cp $SOURCE_INCLUDE_DIR/PksGame.h \
             $SOURCE_INCLUDE_DIR/PksDiceRoller.h \
             $SOURCE_INCLUDE_DIR/PksGameState.h \
             $SOURCE_INCLUDE_DIR/PksColor.h \
             $SOURCE_INCLUDE_DIR/PksRollDiceResult.h \
             $SOURCE_INCLUDE_DIR/PksSpotType.h \
             $SOURCE_INCLUDE_DIR/PksBoardState.h \
             dist/include

          # Push new artifacts to the main branch
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add dist/
          git commit -m "Automatic artifact update ($(date +'%Y-%m-%d'))"
          git push
